import type { AppIconName } from "@/components/ui/AppIcon";

/** Semantic icon keys — same structure as legacy APP_EMOJI, values are AppIconName. */
export const APP_ICON = {
  nav: {
    home: "home",
    daily: "daily",
    calendar: "calendar",
    pipeline: "pipeline",
    retailHouse: "retailHouse",
  },
  hub: {
    dailyAction: "dailyAction",
    goals: "goals",
    leaderboard: "leaderboard",
    pipeline: "pipeline",
    retailHouse: "retailHouse",
    organization: "organization",
    promotions: "promotions",
    calendar: "calendar",
    events: "events",
    preMeetingGraphic: "preMeetingGraphic",
    learning: "learning",
  },
  section: {
    presidentAi: "presidentAi",
    missions: "missions",
    promotion: "promotion",
    achievements: "achievements",
    nextSteps: "nextSteps",
    mapUniverse: "mapUniverse",
    points: "points",
    calendarToday: "calendarToday",
    quickLog: "quickLog",
    superLeague: "superLeague",
    memberProfile: "profile",
    growth: "growth",
    business: "business",
    organization: "organizationHandshake",
    aiAnalysis: "aiAnalysis",
    activity: "activity",
    promotions: "promotionsTarget",
    retailRules: "retailRules",
    groupCompetition: "groupCompetition",
  },
  page: {
    dailyAction: "dailyAction",
    calendar: "calendar",
    retailHouse: "retailHouse",
    leaderboard: "leaderboard",
    organization: "organization",
    pipeline: "pipeline",
    preMeetingGraphic: "preMeetingGraphic",
    events: "events",
    profile: "profile",
    learning: "learning",
    presidentRoad: "presidentRoad",
  },
  action: {
    measurement: "measurement",
    consultation: "consultation",
    recruit: "recruit",
    addRecord: "addRecord",
    presentation: "presentation",
    redeem: "redeem",
    notify: "notify",
  },
  mood: {
    welcome: "welcome",
    empty: "empty",
    done: "done",
    error: "error",
    loading: "loading",
    streak: "streak",
    trophy: "trophy",
  },
  quadrant: {
    newCustomer: "newCustomer",
    returningCustomer: "returningCustomer",
    newMember: "newMember",
    returningMember: "returningMember",
  },
} as const satisfies Record<string, Record<string, AppIconName>>;

export const ROUTE_ICONS: Record<string, AppIconName> = {
  "/": "home",
  "/daily-action": "dailyAction",
  "/goals": "goals",
  "/leaderboard": "leaderboard",
  "/retail-pipeline": "pipeline",
  "/retail-house": "retailHouse",
  "/organization": "organization",
  "/promotions": "promotions",
  "/calendar": "calendar",
  "/events": "events",
  "/pre-meeting-graphic": "preMeetingGraphic",
  "/learning": "learning",
  "/president-road": "presidentRoad",
  "/profile": "profile",
};

export const QUADRANT_ICONS: Record<string, AppIconName> = {
  new_customer: "newCustomer",
  returning_customer: "returningCustomer",
  new_member: "newMember",
  returning_member: "returningMember",
};
