export const STORAGE_KEYS = {
  retailTransactions: "baki-go:retail-transactions",
  computedMetrics: "baki-go:computed-metrics",
  bakiEvents: "baki-go:baki-events",
  eventsMigrated: "baki-go:events-migrated",
  members: "baki-go:members",
  authAccounts: "baki-go:auth-accounts",
  authSession: "baki-go:auth-session",
  memberInBodyRecords: "baki-go:member-inbody-records",
  memberProgressPhotos: "baki-go:member-progress-photos",
  memberCoachNotes: "baki-go:member-coach-notes",
  retailPipelineLeads: "baki-go:retail-pipeline-leads",
  promotionCampaigns: "baki-go:promotion-campaigns",
  calendarEvents: "baki-go:calendar-events",
  calendarSharedAttendance: "baki-go:calendar-shared-attendance",
  sharedCalendarEvents: "baki-go:shared-calendar-events",
  sharedCalendarCacheMeta: "baki-go:shared-calendar-cache-meta",
  sharedCalendarDataVersion: "baki-go:shared-calendar-data-version",
  showSharedCalendar: "baki-go:show-shared-calendar",
  googleCalendarAuth: "baki-go:google-calendar-auth",
  appDataResetVersion: "baki-go:app-data-reset-version",
  pointRedemptions: "baki-go:point-redemptions",
  calendarReminderQueue: "baki-go:calendar-reminder-queue",
  cloudMembersMode: "baki-go:cloud-members-mode",
  superLeagueEntries: "baki-go:super-league-entries",
  memberGoals: "baki-go:member-goals",
  homeDisplayMode: "baki-go:home-display-mode",
} as const;
