export const STORAGE_KEYS = {
  retailTransactions: "baki-go:retail-transactions",
  /** Durable delete markers so merge-first cloud sync cannot resurrect RH rows. */
  retailTransactionDeletionTombstones: "baki-go:retail-transaction-deletion-tombstones",
  computedMetrics: "baki-go:computed-metrics",
  bakiEvents: "baki-go:baki-events",
  eventsMigrated: "baki-go:events-migrated",
  members: "baki-go:members",
  authAccounts: "baki-go:auth-accounts",
  authSession: "baki-go:auth-session",
  memberInBodyRecords: "baki-go:member-inbody-records",
  memberProgressPhotos: "baki-go:member-progress-photos",
  memberCoachNotes: "baki-go:member-coach-notes",
  retailPipelineLeads: "baki-go:retail-pipeline-leads",
  promotionCampaigns: "baki-go:promotion-campaigns",
  calendarEvents: "baki-go:calendar-events",
  calendarEventDeletionTombstones: "baki-go:calendar-event-deletion-tombstones",
  calendarGoogleDeletionTombstones: "baki-go:calendar-google-deletion-tombstones",
  calendarSharedAttendance: "baki-go:calendar-shared-attendance",
  /** Coach-owned customer links to Alliance Shared events (not copied into personal calendar). */
  calendarAllianceEventParticipants: "baki-go:calendar-alliance-event-participants",
  sharedCalendarEvents: "baki-go:shared-calendar-events",
  sharedCalendarCacheMeta: "baki-go:shared-calendar-cache-meta",
  sharedCalendarDataVersion: "baki-go:shared-calendar-data-version",
  showSharedCalendar: "baki-go:show-shared-calendar",
  /** Calendar layout: week starts on monday | sunday. Default monday (production legacy). */
  calendarWeekStart: "baki-go:calendar-week-start",
  googleCalendarAuth: "baki-go:google-calendar-auth",
  appDataResetVersion: "baki-go:app-data-reset-version",
  pointRedemptions: "baki-go:point-redemptions",
  calendarReminderQueue: "baki-go:calendar-reminder-queue",
  cloudMembersMode: "baki-go:cloud-members-mode",
  superLeagueEntries: "baki-go:super-league-entries",
  memberGoals: "baki-go:member-goals",
  homeDisplayMode: "baki-go:home-display-mode",
  customers: "baki-go:customers",
  customerBodyRecords: "baki-go:customer-body-records",
  customerProgressPhotos: "baki-go:customer-progress-photos",
  customerReceiptPhotos: "baki-go:customer-receipt-photos",
  customerDeletionTombstones: "baki-go:customer-deletion-tombstones",
  bodyRecordDeletionTombstones: "baki-go:body-record-deletion-tombstones",
  customerFollowUpReminderDate: "baki-go:customer-follow-up-reminder-date",
  partnerCareMeta: "baki-go:partner-care-meta",
} as const;
